version: "3"
services:
    game-engine:
        image: coderone.azurecr.io/bomberland-engine:2381
        volumes:
            - type: "bind"
              source: ./agents/replay.json
              target: /app/replay.json

    python3-agent:
        build:
            context: agents/python3
            dockerfile: Dockerfile

    python3-agent-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.dev
        volumes:
            - ./agents/python3:/app

    python3-admin-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.admin.dev
        volumes:
            - ./agents/python3:/app

    python3-ppo-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.ppo.dev
        volumes:
            - ./agents/python3:/app

    python3-agent1:
        build:
            context: agents/python3
            dockerfile: Dockerfile.agent1.dev
        volumes:
            - ./agents/python3:/app

    python3-agent2:
        build:
            context: agents/python3
            dockerfile: Dockerfile.agent2.dev
        volumes:
            - ./agents/python3:/app    

    python3-agent3:
        build:
            context: agents/python3
            dockerfile: Dockerfile.agent3.dev
        volumes:
            - ./agents/python3:/app    

    python3-agent4:
        build:
            context: agents/python3
            dockerfile: Dockerfile.agent4.dev
        volumes:
            - ./agents/python3:/app    

    python3-agent5:
        build:
            context: agents/python3
            dockerfile: Dockerfile.agent5.dev
        volumes:
            - ./agents/python3:/app    