version: "3"
services:
    game-engine:
        image: coderone.azurecr.io/bomberland-engine:2381
        volumes:
            - type: "bind"
              source: ./agents/replay.json
              target: /app/replay.json

    python3-agent:
        build:
            context: agents/python3
            dockerfile: Dockerfile

    python3-agent-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.dev
        volumes:
            - ./agents/python3:/app

    python3-fwd:
        build:
            context: agents/python3
            dockerfile: Dockerfile.fwd

    python3-fwd-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.fwd.dev
        volumes:
            - ./agents/python3:/app

    python3-gym-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.gym.dev
        volumes:
            - ./agents/python3:/app

    python3-ml2-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.ml2.dev
        volumes:
            - ./agents/python3:/app

    python3-admin-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.admin.dev
        volumes:
            - ./agents/python3:/app

    python3-ppo-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.ppo.dev
        volumes:
            - ./agents/python3:/app